/*
 * Copyright 2026 nano_com authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * @file nano_tests.c
 * @brief Nano tests.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Use the consolidated ncom API surface. */
#include <ncom/ncom.h>
#include <ncom/plugin_loader.h>

/* Header generated by nidlgen. */
#include "demo.h"

/* Tiny test helpers (no external framework). */
static int g_failed = 0;
static int g_argc = 0;
static char** g_argv = NULL;

#define TEST_CASE(NAME) static void NAME(void)

#define ASSERT_TRUE(COND) do { \
    if (!(COND)) { \
        fprintf(stderr, "ASSERT_TRUE failed at %s:%d: %s\n", __FILE__, __LINE__, #COND); \
        g_failed = 1; \
        return; \
    } \
} while (0)

#define ASSERT_EQ_I32(A,B) do { \
    int32_t _a = (int32_t)(A); \
    int32_t _b = (int32_t)(B); \
    if (_a != _b) { \
        fprintf(stderr, "ASSERT_EQ_I32 failed at %s:%d: %s=%d %s=%d\n", __FILE__, __LINE__, #A, (int)_a, #B, (int)_b); \
        g_failed = 1; \
        return; \
    } \
} while (0)

#define ASSERT_NOT_NULL(P) ASSERT_TRUE((P) != NULL)

/* CHECK helper based on ncom_status_t. */
#define CHECK(expr) do { \
    st = (expr); \
    if (NCOM_FAILED(st)) { \
        fprintf(stderr, "CHECK failed at %s:%d: %s (err: %d)\n", __FILE__, __LINE__, #expr, (int)st); \
        g_failed = 1; \
        goto cleanup; \
    } \
} while (0)


static void default_plugin_path(char* buf, size_t cap)
{
#ifdef _WIN32
    snprintf(buf, cap, "sample_plugin.dll");
#elif __APPLE__
    snprintf(buf, cap, "libsample_plugin.dylib");
#else
    snprintf(buf, cap, "libsample_plugin.so");
#endif
}

static const char* get_plugin_path(int argc, char** argv, char* tmp, size_t cap)
{
    if (argc >= 2 && argv[1] && argv[1][0]) return argv[1];
    default_plugin_path(tmp, cap);
    return tmp;
}

TEST_CASE(test_plugin_load_and_qi)
{
    ncom_status_t st = NCOM_OK;
    ncom_plugin_handle_t* ph = NULL;
    const ncom_plugin_api_v1_t* api = NULL;

    ncom_iunknown_t* u = NULL;
    demo_ilogger_t* log = NULL;
    demo_ilogger2_t* log2 = NULL;
    demo_iclock_t* clk = NULL;
    demo_iclock2_t* clk2 = NULL;
    demo_icapabilities_t* caps = NULL;

    char path[512];
    const char* p = get_plugin_path(g_argc, g_argv, path, sizeof(path));

    CHECK(ncom_plugin_load(p, &ph, &api));
    ASSERT_NOT_NULL(api);

    /* IIDs and CLSIDs are passed by reference (&). */
    CHECK(api->create_instance(&DEMO_CLSID_SAMPLE_COMPONENT, &NCOM_IID_IUNKNOWN, (void**)&u));
    ASSERT_NOT_NULL(u);

    /* Uniform naming for QueryInterface helpers. */
    CHECK(demo_ilogger_qi(u, &log));
    CHECK(demo_ilogger2_qi(u, &log2));
    CHECK(demo_iclock_qi(u, &clk));
    CHECK(demo_iclock2_qi(u, &clk2));
    CHECK(demo_icapabilities_qi(u, &caps));

    /* Smoke calls */
    log->vtbl->log(log, 1, "test_plugin_load_and_qi");
    {
        const char msg2[] = "test via i_logger2::log_view";
        ncom_string_view_t v = { (const uint8_t*)msg2, (uint32_t)(sizeof(msg2) - 1u) };
        CHECK(log2->vtbl->log_view(log2, 1, v));
    }

    int64_t now_ms = 0;
    CHECK(clk->vtbl->now_unix_ms(clk, &now_ms));
    ASSERT_TRUE(now_ms > 0);

    {
        uint32_t major = 0;
        uint32_t minor = 0;
        uint32_t supports_logger2 = 0;
        uint32_t supports_clock2 = 0;
        uint32_t supports_capabilities = 0;
        uint32_t supports_factory = 0;
        CHECK(caps->vtbl->get_api_version(caps, &major, &minor));
        CHECK(caps->vtbl->get_component_capabilities(caps, &supports_logger2,
                                                     &supports_clock2,
                                                     &supports_capabilities,
                                                     &supports_factory));
        ASSERT_TRUE(major >= 1);
        ASSERT_TRUE(supports_logger2 == 1);
        ASSERT_TRUE(supports_factory == 1);
    }

cleanup:
    /* Uniform naming for release helpers. */
    demo_icapabilities_releasep(&caps);
    demo_iclock2_releasep(&clk2);
    demo_iclock_releasep(&clk);
    demo_ilogger2_releasep(&log2);
    demo_ilogger_releasep(&log);
    ncom_iunknown_releasep(&u);
    ncom_plugin_unload(ph);
    ASSERT_EQ_I32(st, NCOM_OK);
}

TEST_CASE(test_error_info_and_string_patterns)
{
    ncom_status_t st = NCOM_OK;
    ncom_plugin_handle_t* ph = NULL;
    const ncom_plugin_api_v1_t* api = NULL;

    ncom_iunknown_t* u = NULL;
    demo_iclock2_t* clk2 = NULL;
    ncom_ierror_info_t* err = NULL;
    ncom_istring_t* s = NULL;

    char path[512];
    const char* p = get_plugin_path(g_argc, g_argv, path, sizeof(path));

    CHECK(ncom_plugin_load(p, &ph, &api));
    CHECK(api->create_instance(&DEMO_CLSID_SAMPLE_COMPONENT, &NCOM_IID_IUNKNOWN, (void**)&u));
    CHECK(demo_iclock2_qi(u, &clk2));

    /* Force an error: pass NULL out_ms. */
    st = clk2->vtbl->now_unix_ms(clk2, NULL, &err);
    ASSERT_EQ_I32(st, NCOM_E_INVALID_ARG);
    ASSERT_NOT_NULL(err);

    /* ncom_istring */
    CHECK(err->vtbl->get_message_string(err, &s));
    ASSERT_NOT_NULL(s);

    const char* sptr = NULL;
    CHECK(s->vtbl->c_str(s, &sptr));
    ASSERT_TRUE(sptr != NULL && strlen(sptr) > 0);

    /* Caller-buffer sizing call + copy with ncom_char_buf_t. */
    uint64_t need = 0;
    ncom_char_buf_t cbuf = { 0 }; /* Empty buffer triggers sizing mode. */

    CHECK(err->vtbl->get_message_buf(err, &cbuf, &need));
    ASSERT_TRUE(need >= 2 && need < 1024);

    char* buf = (char*)calloc((size_t)need, 1);
    ASSERT_NOT_NULL(buf);

    /* Initialize caller buffer and call again. */
    cbuf.ptr = buf;
    cbuf.cap = need;
    st = err->vtbl->get_message_buf(err, &cbuf, &need);
    ASSERT_EQ_I32(st, NCOM_OK);
    ASSERT_TRUE(strlen(buf) > 0);

    free(buf);
    st = NCOM_OK;

cleanup:
    ncom_istring_releasep(&s);
    ncom_ierror_info_releasep(&err);
    demo_iclock2_releasep(&clk2);
    ncom_iunknown_releasep(&u);
    ncom_plugin_unload(ph);
    ASSERT_EQ_I32(st, NCOM_OK);
}

TEST_CASE(test_refcount_basic)
{
    ncom_status_t st = NCOM_OK;
    ncom_plugin_handle_t* ph = NULL;
    const ncom_plugin_api_v1_t* api = NULL;

    demo_ilogger_t* log = NULL;
    demo_iclock_t* clk = NULL;

    char path[512];
    const char* p = get_plugin_path(g_argc, g_argv, path, sizeof(path));

    CHECK(ncom_plugin_load(p, &ph, &api));

    /* Create as ILogger directly: initial refcount should be 1. */
    CHECK(api->create_instance(&DEMO_CLSID_SAMPLE_COMPONENT, &DEMO_IID_ILOGGER, (void**)&log));
    ASSERT_NOT_NULL(log);

    uint32_t rc = log->vtbl->base.add_ref((ncom_iunknown_t*)log);
    ASSERT_TRUE(rc >= 2);

    /* Query another view increments the same underlying refcount. */
    CHECK(log->vtbl->base.query_interface((ncom_iunknown_t*)log, &DEMO_IID_ICLOCK, (void**)&clk));
    ASSERT_NOT_NULL(clk);

    /* Release clock view, then release logger view twice (for add_ref + initial). */
    rc = clk->vtbl->base.release((ncom_iunknown_t*)clk);
    ASSERT_TRUE(rc >= 1);
    clk = NULL; /* prevent double-release in cleanup */

    rc = log->vtbl->base.release((ncom_iunknown_t*)log); /* undo add_ref */
    ASSERT_TRUE(rc >= 1);

    rc = log->vtbl->base.release((ncom_iunknown_t*)log); /* final release */
    (void)rc;
    log = NULL;

cleanup:
    demo_iclock_releasep(&clk);
    demo_ilogger_releasep(&log);
    ncom_plugin_unload(ph);
    ASSERT_EQ_I32(st, NCOM_OK);
}

TEST_CASE(test_plugin_load_missing_file)
{
    ncom_status_t st = NCOM_OK;
    ncom_plugin_handle_t* ph = NULL;
    const ncom_plugin_api_v1_t* api = NULL;

#ifdef _WIN32
    st = ncom_plugin_load("this_file_does_not_exist_12345.dll", &ph, &api);
#else
    st = ncom_plugin_load("this_file_does_not_exist_12345.so", &ph, &api);
#endif

    ASSERT_TRUE(NCOM_FAILED(st));
    ASSERT_TRUE(ph == NULL);
    ASSERT_TRUE(api == NULL);
}

TEST_CASE(test_factory_contract)
{
    ncom_status_t st = NCOM_OK;
    ncom_plugin_handle_t* ph = NULL;
    const ncom_plugin_api_v1_t* api = NULL;
    demo_icomponent_factory_t* fac = NULL;
    ncom_iunknown_t* u = NULL;
    demo_iclock_t* clk = NULL;
    ncom_ierror_info_t* err = NULL;

    char path[512];
    const char* p = get_plugin_path(g_argc, g_argv, path, sizeof(path));

    CHECK(ncom_plugin_load(p, &ph, &api));
    CHECK(api->create_instance(&DEMO_CLSID_SAMPLE_COMPONENT_FACTORY,
                               &DEMO_IID_ICOMPONENT_FACTORY, (void**)&fac));
    ASSERT_NOT_NULL(fac);

    CHECK(fac->vtbl->create_sample_component(fac, &DEMO_IID_ICLOCK, &u, &err));
    ASSERT_NOT_NULL(u);
    CHECK(demo_iclock_qi(u, &clk));
    ASSERT_NOT_NULL(clk);

    int64_t now_ms = 0;
    CHECK(clk->vtbl->now_unix_ms(clk, &now_ms));
    ASSERT_TRUE(now_ms > 0);

cleanup:
    ncom_ierror_info_releasep(&err);
    demo_iclock_releasep(&clk);
    ncom_iunknown_releasep(&u);
    demo_icomponent_factory_releasep(&fac);
    ncom_plugin_unload(ph);
    ASSERT_EQ_I32(st, NCOM_OK);
}

int main(int argc, char** argv)
{
    g_argc = argc;
    g_argv = argv;

    test_plugin_load_and_qi();
    test_error_info_and_string_patterns();
    test_refcount_basic();
    test_plugin_load_missing_file();
    test_factory_contract();

    if (g_failed) {
        fprintf(stderr, "nano_tests: FAILED\n");
        return 1;
    }
    fprintf(stderr, "nano_tests: OK\n");
    return 0;
}
